-- ==============================================================================
-- Schema: Micro SaaS Cop Stamp (Digital Loyalty Stamp System)
-- ==============================================================================

-- 1. Enable UUID Extension
create extension if not exists "uuid-ossp";

-- 2. Stores Table
create table if not exists public.stores (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    stamps_required int not null default 10 check (stamps_required > 0),
    reward_description text not null default '1 minuman panas percuma (saiz regular)',
    logo_url text,
    reward_image_url text,
    rewards jsonb default '[]'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Backward compatibility columns
alter table public.stores add column if not exists logo_url text;
alter table public.stores add column if not exists reward_image_url text;
alter table public.stores add column if not exists rewards jsonb default '[]'::jsonb;

-- Subscription & Stripe columns
alter table public.stores add column if not exists plan_type text default 'free';
alter table public.stores add column if not exists subscription_status text default 'active';
alter table public.stores add column if not exists stripe_customer_id text;
alter table public.stores add column if not exists stripe_subscription_id text;
alter table public.stores add column if not exists subscription_end_date timestamptz;


-- 3. Store Staff Table (cashiers and owners)
create table if not exists public.store_staff (
    id uuid primary key default gen_random_uuid(),
    store_id uuid not null references public.stores(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    role text not null default 'cashier' check (role in ('owner', 'cashier')),
    created_at timestamptz not null default now(),
    unique(store_id, user_id)
);

-- 4. Customer Profiles Table
create table if not exists public.customer_profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text,
    full_name text,
    avatar_url text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_customer_profiles_email on public.customer_profiles(email);

-- 5. Stamp Tokens Table (one-time use claim tokens generated by cashiers)
create table if not exists public.stamp_tokens (
    id uuid primary key default gen_random_uuid(),
    token text unique not null,
    store_id uuid not null references public.stores(id) on delete cascade,
    stamp_count int not null default 1 check (stamp_count > 0),
    status text not null default 'pending' check (status in ('pending', 'claimed', 'expired')),
    delivery_method text not null default 'qr' check (delivery_method in ('qr', 'email')),
    recipient_email text,
    created_by uuid references auth.users(id),
    claimed_by uuid references auth.users(id),
    claimed_at timestamptz,
    expires_at timestamptz not null default (now() + interval '30 minutes'),
    created_at timestamptz not null default now()
);

create index if not exists idx_stamp_tokens_token on public.stamp_tokens(token);
create index if not exists idx_stamp_tokens_store_id on public.stamp_tokens(store_id);
create index if not exists idx_stamp_tokens_status on public.stamp_tokens(status);

-- 6. Customer Loyalty Table (tracks total stamp points per customer per store)
create table if not exists public.customer_loyalty (
    id uuid primary key default gen_random_uuid(),
    customer_id uuid not null references auth.users(id) on delete cascade,
    store_id uuid not null references public.stores(id) on delete cascade,
    total_stamps int not null default 0 check (total_stamps >= 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(customer_id, store_id)
);

create index if not exists idx_customer_loyalty_lookup on public.customer_loyalty(customer_id, store_id);

-- 7. Stamp Redemptions Table (records when customer claims rewards)
create table if not exists public.stamp_redemptions (
    id uuid primary key default gen_random_uuid(),
    customer_id uuid not null references auth.users(id) on delete cascade,
    customer_email text,
    store_id uuid not null references public.stores(id) on delete cascade,
    stamps_used int not null check (stamps_used > 0),
    reward_details text,
    redeemed_by uuid references auth.users(id),
    created_at timestamptz not null default now()
);

create index if not exists idx_stamp_redemptions_store on public.stamp_redemptions(store_id, created_at desc);

-- ==============================================================================
-- Row Level Security (RLS) Policies
-- ==============================================================================

alter table public.stores enable row level security;
alter table public.store_staff enable row level security;
alter table public.customer_profiles enable row level security;
alter table public.stamp_tokens enable row level security;
alter table public.customer_loyalty enable row level security;
alter table public.stamp_redemptions enable row level security;

-- Stores policies
create policy "Allow anyone to read store info"
    on public.stores for select
    using (true);

-- CATATAN: sengaja TIADA policy INSERT untuk public.stores.
-- Pendaftaran kedai baharu (onboarding) hanya berlaku melalui
-- POST /api/store/settings, yang guna service-role admin client
-- (bypass RLS) selepas semakan auth + existingStaff di app layer.
-- Jangan tambah "with check (auth.uid() is not null)" — itu benarkan
-- SESIAPA authenticated insert terus ke stores via PostgREST, bypass
-- app sepenuhnya.

create policy "Allow store owners to update store settings"
    on public.stores for update
    using (
        exists (
            select 1 from public.store_staff
            where store_staff.store_id = stores.id
              and store_staff.user_id = auth.uid()
              and store_staff.role = 'owner'
        )
    );

-- Store Staff policies
create policy "Allow staff to see their own store memberships"
    on public.store_staff for select
    using (user_id = auth.uid());

-- CATATAN: sengaja TIADA policy INSERT untuk public.store_staff.
-- Pemautan staf/owner ke kedai hanya berlaku melalui
-- POST /api/store/settings (admin client, bypass RLS, dengan semakan
-- app-level). JANGAN tambah policy insert dengan
-- "with check (user_id = auth.uid())" sahaja — ia tak restrict
-- store_id, jadi sesiapa authenticated boleh jadikan diri sendiri
-- 'owner' bagi MANA-MANA store_id sedia ada (privilege escalation
-- kritikal, exploitable terus via PostgREST anon key).

-- Customer Profiles policies
create policy "Allow users to view customer profiles"
    on public.customer_profiles for select
    using (true);

create policy "Allow users to update own profile"
    on public.customer_profiles for update
    using (id = auth.uid());

create policy "Allow users to insert own profile"
    on public.customer_profiles for insert
    with check (id = auth.uid());

-- Stamp Tokens policies
create policy "Allow store staff to view store tokens"
    on public.stamp_tokens for select
    using (
        exists (
            select 1 from public.store_staff
            where store_staff.store_id = stamp_tokens.store_id
              and store_staff.user_id = auth.uid()
        )
    );

-- KEKAL SENGAJA: policy ni memang design "sesiapa dengan link/token
-- boleh claim". Dibincang & disahkan oleh pemilik projek — tidak ditukar.
create policy "Allow anyone to view token validation status"
    on public.stamp_tokens for select
    using (true);

create policy "Allow store staff to insert tokens"
    on public.stamp_tokens for insert
    with check (
        exists (
            select 1 from public.store_staff
            where store_staff.store_id = stamp_tokens.store_id
              and store_staff.user_id = auth.uid()
        )
    );

-- Customer Loyalty policies
create policy "Customers can view their own loyalty balance"
    on public.customer_loyalty for select
    using (customer_id = auth.uid());

create policy "Staff can view loyalty of customers in their store"
    on public.customer_loyalty for select
    using (
        exists (
            select 1 from public.store_staff
            where store_staff.store_id = customer_loyalty.store_id
              and store_staff.user_id = auth.uid()
        )
    );

-- Stamp Redemptions policies
create policy "Customers can view their own redemptions"
    on public.stamp_redemptions for select
    using (customer_id = auth.uid());

create policy "Staff can view redemptions in their store"
    on public.stamp_redemptions for select
    using (
        exists (
            select 1 from public.store_staff
            where store_staff.store_id = stamp_redemptions.store_id
              and store_staff.user_id = auth.uid()
        )
    );

-- ==============================================================================
-- Auth Trigger: Auto-create customer profile on auth.users creation
-- ==============================================================================

create or replace function public.handle_new_customer()
returns trigger as $$
begin
  insert into public.customer_profiles (id, email, full_name, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (id) do update
  set
    email = coalesce(excluded.email, customer_profiles.email),
    full_name = coalesce(excluded.full_name, customer_profiles.full_name),
    avatar_url = coalesce(excluded.avatar_url, customer_profiles.avatar_url),
    updated_at = now();
  return new;
end;
$$ language plpgsql security definer
set search_path = public, pg_temp;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_customer();

-- ==============================================================================
-- RPC Function: claim_stamp_token (Atomic Token Claim)
-- ==============================================================================

create or replace function public.claim_stamp_token(p_token text)
returns jsonb as $$
declare
    v_customer_id uuid;
    v_token_row public.stamp_tokens%ROWTYPE;
    v_store_row public.stores%ROWTYPE;
    v_prev_stamps int := 0;
    v_new_stamps int := 0;
begin
    -- 1. Check authenticated user
    v_customer_id := auth.uid();
    if v_customer_id is null then
        return jsonb_build_object(
            'success', false,
            'error', 'unauthenticated',
            'message', 'Sila log masuk untuk menebus cop stamp.'
        );
    end if;

    -- 2. Lock & fetch token
    select * into v_token_row
    from public.stamp_tokens
    where token = p_token
    for update;

    if not found then
        return jsonb_build_object(
            'success', false,
            'error', 'not_found',
            'message', 'Pautan cop ini tidak sah atau tidak wujud.'
        );
    end if;

    -- 3. Validate token status
    if v_token_row.status = 'claimed' then
        return jsonb_build_object(
            'success', false,
            'error', 'already_claimed',
            'message', 'Cop ini sudah diambil sebelum ini.'
        );
    end if;

    if v_token_row.expires_at < now() or v_token_row.status = 'expired' then
        update public.stamp_tokens
        set status = 'expired'
        where id = v_token_row.id;

        return jsonb_build_object(
            'success', false,
            'error', 'expired',
            'message', 'Pautan ini telah luput tempoh (sah 15 minit sahaja).'
        );
    end if;

    -- 4. Get store information
    select * into v_store_row
    from public.stores
    where id = v_token_row.store_id;

    -- 5. Get current loyalty balance
    select coalesce(total_stamps, 0) into v_prev_stamps
    from public.customer_loyalty
    where customer_id = v_customer_id
      and store_id = v_token_row.store_id;

    if v_prev_stamps is null then
        v_prev_stamps := 0;
    end if;

    v_new_stamps := v_prev_stamps + v_token_row.stamp_count;

    -- 6. Upsert customer loyalty balance
    insert into public.customer_loyalty (customer_id, store_id, total_stamps, updated_at)
    values (v_customer_id, v_token_row.store_id, v_new_stamps, now())
    on conflict (customer_id, store_id)
    do update set
        total_stamps = public.customer_loyalty.total_stamps + v_token_row.stamp_count,
        updated_at = now();

    -- 7. Mark token as claimed
    update public.stamp_tokens
    set
        status = 'claimed',
        claimed_by = v_customer_id,
        claimed_at = now()
    where id = v_token_row.id;

    -- 8. Return comprehensive payload for frontend animations
    return jsonb_build_object(
        'success', true,
        'storeId', v_token_row.store_id,
        'stampsAdded', v_token_row.stamp_count,
        'previousStamps', v_prev_stamps,
        'newTotal', v_new_stamps,
        'storeName', coalesce(v_store_row.name, 'Kedai'),
        'stampsRequired', coalesce(v_store_row.stamps_required, 10),
        'rewardDescription', coalesce(v_store_row.reward_description, '1 ganjaran istimewa')
    );
end;
$$ language plpgsql security definer
set search_path = public, pg_temp;

-- ==============================================================================
-- Rate Limiting: persistent table + atomic RPC (ganti in-memory Map di
-- lib/rate-limit.ts, yang tak reliable merentasi instance serverless)
-- ==============================================================================

create table if not exists public.api_rate_limits (
    identifier text primary key,
    count int not null default 1,
    reset_time timestamptz not null
);

-- Table ni hanya diakses melalui service-role client (admin) dari server,
-- jadi tak perlu RLS/anon access. Enable RLS tanpa policy = deny-by-default
-- untuk anon/authenticated; service role sentiasa bypass RLS.
alter table public.api_rate_limits enable row level security;

create or replace function public.check_rate_limit(
    p_identifier text,
    p_max_requests int,
    p_window_seconds int
)
returns jsonb as $$
declare
    v_now timestamptz := now();
    v_record public.api_rate_limits%ROWTYPE;
begin
    select * into v_record
    from public.api_rate_limits
    where identifier = p_identifier
    for update;

    -- Tiada rekod, atau window sebelumnya dah tamat -> mula window baru
    if not found or v_record.reset_time < v_now then
        insert into public.api_rate_limits (identifier, count, reset_time)
        values (p_identifier, 1, v_now + make_interval(secs => p_window_seconds))
        on conflict (identifier) do update
        set count = 1,
            reset_time = excluded.reset_time
        returning * into v_record;

        return jsonb_build_object(
            'success', true,
            'remaining', p_max_requests - 1,
            'reset', floor(extract(epoch from v_record.reset_time) * 1000)
        );
    end if;

    if v_record.count >= p_max_requests then
        return jsonb_build_object(
            'success', false,
            'remaining', 0,
            'reset', floor(extract(epoch from v_record.reset_time) * 1000)
        );
    end if;

    update public.api_rate_limits
    set count = count + 1
    where identifier = p_identifier
    returning * into v_record;

    return jsonb_build_object(
        'success', true,
        'remaining', p_max_requests - v_record.count,
        'reset', floor(extract(epoch from v_record.reset_time) * 1000)
    );
end;
$$ language plpgsql security definer
set search_path = public, pg_temp;

-- ==============================================================================
-- RPC Function: redeem_reward_atomic (Cashier Redeems Customer Stamp Reward)
-- ==============================================================================

create or replace function public.redeem_reward_atomic(
    p_customer_id uuid,
    p_store_id uuid,
    p_reward_count int default 1
)
returns jsonb as $$
declare
    v_staff_id uuid;
    v_store public.stores%ROWTYPE;
    v_loyalty public.customer_loyalty%ROWTYPE;
    v_customer_profile public.customer_profiles%ROWTYPE;
    v_stamps_needed int;
    v_new_stamps int;
begin
    v_staff_id := auth.uid();
    if v_staff_id is null then
        return jsonb_build_object('success', false, 'error', 'unauthenticated', 'message', 'Sila log masuk.');
    end if;

    -- Verify cashier has access to store
    if not exists (
        select 1 from public.store_staff
        where store_id = p_store_id and user_id = v_staff_id
    ) then
        return jsonb_build_object('success', false, 'error', 'forbidden', 'message', 'Tiada kebenaran untuk kedai ini.');
    end if;

    -- Get store details
    select * into v_store from public.stores where id = p_store_id;
    if not found then
        return jsonb_build_object('success', false, 'error', 'store_not_found', 'message', 'Kedai tidak dijumpai.');
    end if;

    -- Lock customer loyalty record
    select * into v_loyalty
    from public.customer_loyalty
    where customer_id = p_customer_id and store_id = p_store_id
    for update;

    if not found then
        return jsonb_build_object('success', false, 'error', 'no_stamps', 'message', 'Pelanggan belum mempunyai rekod cop di kedai ini.');
    end if;

    v_stamps_needed := v_store.stamps_required * coalesce(p_reward_count, 1);

    if v_loyalty.total_stamps < v_stamps_needed then
        return jsonb_build_object(
            'success', false,
            'error', 'insufficient_stamps',
            'message', format('Cop tidak mencukupi (%s/%s diperlukan).', v_loyalty.total_stamps, v_stamps_needed),
            'totalStamps', v_loyalty.total_stamps,
            'stampsRequired', v_store.stamps_required
        );
    end if;

    -- Deduct stamps
    v_new_stamps := v_loyalty.total_stamps - v_stamps_needed;
    update public.customer_loyalty
    set total_stamps = v_new_stamps, updated_at = now()
    where customer_id = p_customer_id and store_id = p_store_id;

    -- Fetch customer profile
    select * into v_customer_profile from public.customer_profiles where id = p_customer_id;

    -- Insert redemption record
    insert into public.stamp_redemptions (
        customer_id,
        customer_email,
        store_id,
        stamps_used,
        reward_details,
        redeemed_by,
        created_at
    )
    values (
        p_customer_id,
        v_customer_profile.email,
        p_store_id,
        v_stamps_needed,
        v_store.reward_description,
        v_staff_id,
        now()
    );

    return jsonb_build_object(
        'success', true,
        'message', 'Ganjaran berjaya ditebus!',
        'previousStamps', v_loyalty.total_stamps,
        'stampsUsed', v_stamps_needed,
        'remainingStamps', v_new_stamps,
        'rewardDescription', v_store.reward_description,
        'customerEmail', v_customer_profile.email
    );
end;
$$ language plpgsql security definer
set search_path = public, pg_temp;
